# Disable MD060 (table-column-style) - tables have variable content that conflicts with aligned/compact rules
MD060: false
# Allow longer lines - reference docs, links, and tables often exceed 180 chars
MD013:
  line_length: 300
