# Disable MD060 (table-column-style) - tables have variable content that conflicts with aligned/compact rules
MD060: false
# Allow longer lines - reference docs and tables often exceed 80 chars
MD013:
  line_length: 180
